import { z } from "zod";
import type { HmacRef } from "@/application/conversation-v2/comparison-record";

export const CYCLE_I_GATE_REPORT_VERSION = "conversation-v2-cycle-i-gate.v1" as const;
const names = ["h_entailment", "shadow_no_effects", "protocol_integrity", "supported_understanding", "supported_decision", "critical_regressions", "qualitative", "full_turn_cost", "full_turn_p95", "rollback", "observability", "verification", "adversarial_review"] as const;
type CriterionName = typeof names[number];
type Status = "pass" | "fail" | "not_measurable" | "pending_human_review";
type Evidence = Readonly<{ evidenceDigest: HmacRef | null; populationDigest: HmacRef; datasetDigest: HmacRef; configDigest: HmacRef }>;
export type CycleIGateCriterion = Readonly<{ status: Status; layer: string; population: string; denominator: number; applicable: true; blocking: true } & Evidence>;
export type CycleIGateReport = Readonly<{ version: typeof CYCLE_I_GATE_REPORT_VERSION; reportDigest: HmacRef; populationDigest: HmacRef; datasetDigest: HmacRef; configDigest: HmacRef; judge: "experimental_non_gating"; criteria: Readonly<Record<CriterionName, CycleIGateCriterion>>; decision: "GO" | "NO_GO" }>;
export type CycleIGateInputs = Readonly<{ reportDigest: string; populationDigest: string; datasetDigest: string; configDigest: string; measurements?: Partial<Record<CriterionName, unknown>> }>;
const hmac = z.string().regex(/^hmac:[a-f0-9]{64}$/, "invalid HmacRef");
const spec = Object.freeze({
  h_entailment: { layer: "cycles_a_to_h", population: "h-entailment", denominator: 1 }, shadow_no_effects: { layer: "shadow", population: "all-shadow-observations", denominator: 1 }, protocol_integrity: { layer: "corpus", population: "cycle-f-supported-dental-corpus", denominator: 204 }, supported_understanding: { layer: "understanding", population: "cycle-f-supported-dental-corpus", denominator: 102 }, supported_decision: { layer: "decision", population: "approved-decision-receipts", denominator: 1 }, critical_regressions: { layer: "safety", population: "stable-primary-and-d0-sensitivity", denominator: 204 }, qualitative: { layer: "prose", population: "blind-human-review", denominator: 1 }, full_turn_cost: { layer: "performance", population: "approved-replay-or-lab", denominator: 1 }, full_turn_p95: { layer: "performance", population: "approved-replay-or-lab", denominator: 1 }, rollback: { layer: "activation", population: "test-tenant-selector", denominator: 1 }, observability: { layer: "observability", population: "minimum-required-fields", denominator: 1 }, verification: { layer: "verification", population: "required-suite", denominator: 1 }, adversarial_review: { layer: "review", population: "independent-adversarial-review", denominator: 1 },
} as Record<CriterionName, Readonly<{ layer: string; population: string; denominator: number }>>);
for (const name of names) Object.freeze(spec[name]);
const evidenceSchema = z.object({ evidenceDigest: hmac.optional(), populationDigest: hmac.optional(), datasetDigest: hmac.optional(), configDigest: hmac.optional(), denominator: z.number().int().positive().optional() }).strict();
const measurements = {
  h_entailment: evidenceSchema.extend({ passed: z.boolean() }).strict(), shadow_no_effects: evidenceSchema.extend({ sideEffects: z.number().int().min(0), contamination: z.number().int().min(0) }).strict(), protocol_integrity: evidenceSchema.extend({ completedObservations: z.number().int().min(0) }).strict(), supported_understanding: evidenceSchema.extend({ v1Correct: z.number().int().min(0), v2Correct: z.number().int().min(0) }).strict(), supported_decision: evidenceSchema.extend({ matches: z.number().int().min(0) }).strict(), critical_regressions: evidenceSchema.extend({ count: z.number().int().min(0) }).strict(), qualitative: evidenceSchema.extend({ completed: z.boolean(), v1Positive: z.number().int().min(0), v2Positive: z.number().int().min(0) }).strict(), full_turn_cost: evidenceSchema.extend({ v1MeanMinor: z.number().int().min(0), v2MeanMinor: z.number().int().min(0) }).strict(), full_turn_p95: evidenceSchema.extend({ v1P95Ms: z.number().int().min(0), v2P95Ms: z.number().int().min(0) }).strict(), rollback: evidenceSchema.extend({ passed: z.boolean() }).strict(), observability: evidenceSchema.extend({ passed: z.boolean() }).strict(), verification: evidenceSchema.extend({ passed: z.boolean() }).strict(), adversarial_review: evidenceSchema.extend({ passed: z.boolean() }).strict(),
} satisfies Record<CriterionName, z.ZodTypeAny>;
const criterionSchema = z.object({ status: z.enum(["pass", "fail", "not_measurable", "pending_human_review"]), layer: z.string(), population: z.string(), denominator: z.number().int().positive(), applicable: z.literal(true), blocking: z.literal(true), evidenceDigest: hmac.nullable(), populationDigest: hmac, datasetDigest: hmac, configDigest: hmac }).strict();
const reportSchema = z.object({ version: z.literal(CYCLE_I_GATE_REPORT_VERSION), reportDigest: hmac, populationDigest: hmac, datasetDigest: hmac, configDigest: hmac, judge: z.literal("experimental_non_gating"), criteria: z.object(Object.fromEntries(names.map((name) => [name, criterionSchema])) as Record<CriterionName, typeof criterionSchema>).strict(), decision: z.enum(["GO", "NO_GO"]) }).strict();
function freeze<T>(value: T): T { if (Array.isArray(value)) value.forEach(freeze); else if (value && typeof value === "object") Object.values(value as Record<string, unknown>).forEach(freeze); return Object.freeze(value); }
function measuredPass(name: CriterionName, value: Record<string, unknown>): boolean { const denominator = spec[name].denominator; switch (name) { case "h_entailment": case "rollback": case "observability": case "verification": case "adversarial_review": return value.passed === true; case "shadow_no_effects": return value.sideEffects === 0 && value.contamination === 0; case "protocol_integrity": return value.completedObservations === denominator; case "supported_understanding": return (value.v1Correct as number) <= denominator && (value.v2Correct as number) <= denominator && (value.v2Correct as number) >= (value.v1Correct as number); case "supported_decision": return value.matches === denominator; case "critical_regressions": return value.count === 0; case "qualitative": return value.completed === true && (value.v2Positive as number) >= (value.v1Positive as number); case "full_turn_cost": return (value.v2MeanMinor as number) <= (value.v1MeanMinor as number); case "full_turn_p95": return (value.v2P95Ms as number) <= (value.v1P95Ms as number); } }
function validEvidence(value: Record<string, unknown>, input: { populationDigest: HmacRef; datasetDigest: HmacRef; configDigest: HmacRef }, denominator: number): value is Record<string, unknown> & { evidenceDigest: HmacRef } { return hmac.safeParse(value.evidenceDigest).success && value.populationDigest === input.populationDigest && value.datasetDigest === input.datasetDigest && value.configDigest === input.configDigest && value.denominator === denominator; }
function derive(name: CriterionName, raw: unknown, input: { populationDigest: HmacRef; datasetDigest: HmacRef; configDigest: HmacRef }): CycleIGateCriterion { const fixed = spec[name]; const common = { ...fixed, applicable: true as const, blocking: true as const, populationDigest: input.populationDigest, datasetDigest: input.datasetDigest, configDigest: input.configDigest }; if (raw === undefined) return freeze({ ...common, status: "not_measurable" as const, evidenceDigest: null }); const value = measurements[name].parse(raw) as Record<string, unknown>; if (name === "qualitative" && value.completed === false) return freeze({ ...common, status: "pending_human_review" as const, evidenceDigest: null }); if (!validEvidence(value, input, fixed.denominator)) return freeze({ ...common, status: "not_measurable" as const, evidenceDigest: null }); return freeze({ ...common, status: measuredPass(name, value) ? "pass" as const : "fail" as const, evidenceDigest: value.evidenceDigest }); }
function decision(criteria: Readonly<Record<CriterionName, CycleIGateCriterion>>) { return names.every((name) => criteria[name].status === "pass") ? "GO" as const : "NO_GO" as const; }
export function buildCycleIGateReport(input: CycleIGateInputs): CycleIGateReport { const context = { populationDigest: hmac.parse(input.populationDigest) as HmacRef, datasetDigest: hmac.parse(input.datasetDigest) as HmacRef, configDigest: hmac.parse(input.configDigest) as HmacRef }; const criteria = {} as Record<CriterionName, CycleIGateCriterion>; for (const name of names) criteria[name] = derive(name, input.measurements?.[name], context); return freeze({ version: CYCLE_I_GATE_REPORT_VERSION, reportDigest: hmac.parse(input.reportDigest) as HmacRef, ...context, judge: "experimental_non_gating" as const, criteria: freeze(criteria), decision: decision(criteria) }); }
export function parseCycleIGateReport(input: unknown): CycleIGateReport { const report = reportSchema.parse(input) as CycleIGateReport; for (const name of names) { const actual = report.criteria[name], fixed = spec[name]; if (actual.layer !== fixed.layer || actual.population !== fixed.population || actual.denominator !== fixed.denominator || actual.populationDigest !== report.populationDigest || actual.datasetDigest !== report.datasetDigest || actual.configDigest !== report.configDigest) throw new Error(`immutable applicability or evidence mismatch: ${name}`); if ((actual.status === "pass" || actual.status === "fail") && actual.evidenceDigest === null) throw new Error(`measured gate lacks evidence: ${name}`); } if (report.decision !== decision(report.criteria)) throw new Error("GO decision conflicts with a blocking gate"); return freeze(report); }
