import { db } from "../src/infrastructure/db/client";
import { ConversationOrchestrator } from "../src/core/pipeline/ConversationOrchestrator";

async function run() {
  console.log("Starting simulation test...");
  
  const orchestrator = new ConversationOrchestrator();
  
  try {
    const result = await orchestrator.handle({
      clinicId: "d24a584a-faac-4a46-9750-a718d0f8e686", // Vitalli
      phone: "5511" + Math.floor(Math.random() * 100000000).toString().padStart(8, '0'),
      messageText: "Olá! vi o anúncio e quero saber como posso transformar meu sorriso com facetas de resina?",
      messageId: "fake-msg-" + Date.now(),
      senderName: "Amanda Lead",
      timestamp: new Date(),
    });
    
    // Fetch the inserted messages to see what it generated
    const { conversations, messages } = await import("../src/infrastructure/db/schema");
    const { eq, asc, desc } = await import("drizzle-orm");
    const latestConv = await db.select().from(conversations).orderBy(desc(conversations.createdAt)).limit(1);
    const convId = latestConv[0].id;
    const recentMsgs = await db.select().from(messages).where(eq(messages.conversationId, convId)).orderBy(asc(messages.createdAt));
    console.log("Recent messages generated by AI:");
    recentMsgs.forEach(m => console.log(`[${m.author}] ${m.body}`));
    
    console.log("Orchestrator finished:", result);
  } catch (err) {
    console.error("Orchestrator threw error:", err);
  }
  
  process.exit(0);
}

run().catch(console.error);
